/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PostsRouteImport } from './routes/posts'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DemoSimpleTableRouteImport } from './routes/demo/simple-table'
import { Route as AuthenticatedHomeRouteImport } from './routes/_authenticated.home'
import { Route as DemoStartApiRequestRouteImport } from './routes/demo/start.api-request'
import { Route as DemoApiNamesRouteImport } from './routes/demo/api.names'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AuthenticatedHomeProgramsRouteImport } from './routes/_authenticated.home.programs'
import { Route as AuthenticatedHomeClientsRouteImport } from './routes/_authenticated.home.clients'
import { Route as DemoStartSsrFullSsrRouteImport } from './routes/demo/start.ssr.full-ssr'
import { Route as DemoStartSsrDataOnlyRouteImport } from './routes/demo/start.ssr.data-only'
import { Route as AuthenticatedHomeSettingsExercisesLibraryRouteImport } from './routes/_authenticated/home/settings/exercises/library'
import { Route as AuthenticatedHomeSettingsExercisesConfigurationRouteImport } from './routes/_authenticated/home/settings/exercises/configuration'

const PostsRoute = PostsRouteImport.update({
  id: '/posts',
  path: '/posts',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoSimpleTableRoute = DemoSimpleTableRouteImport.update({
  id: '/demo/simple-table',
  path: '/demo/simple-table',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedHomeRoute = AuthenticatedHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const DemoStartApiRequestRoute = DemoStartApiRequestRouteImport.update({
  id: '/demo/start/api-request',
  path: '/demo/start/api-request',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoApiNamesRoute = DemoApiNamesRouteImport.update({
  id: '/demo/api/names',
  path: '/demo/api/names',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedHomeProgramsRoute =
  AuthenticatedHomeProgramsRouteImport.update({
    id: '/programs',
    path: '/programs',
    getParentRoute: () => AuthenticatedHomeRoute,
  } as any)
const AuthenticatedHomeClientsRoute =
  AuthenticatedHomeClientsRouteImport.update({
    id: '/clients',
    path: '/clients',
    getParentRoute: () => AuthenticatedHomeRoute,
  } as any)
const DemoStartSsrFullSsrRoute = DemoStartSsrFullSsrRouteImport.update({
  id: '/demo/start/ssr/full-ssr',
  path: '/demo/start/ssr/full-ssr',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrDataOnlyRoute = DemoStartSsrDataOnlyRouteImport.update({
  id: '/demo/start/ssr/data-only',
  path: '/demo/start/ssr/data-only',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedHomeSettingsExercisesLibraryRoute =
  AuthenticatedHomeSettingsExercisesLibraryRouteImport.update({
    id: '/settings/exercises/library',
    path: '/settings/exercises/library',
    getParentRoute: () => AuthenticatedHomeRoute,
  } as any)
const AuthenticatedHomeSettingsExercisesConfigurationRoute =
  AuthenticatedHomeSettingsExercisesConfigurationRouteImport.update({
    id: '/settings/exercises/configuration',
    path: '/settings/exercises/configuration',
    getParentRoute: () => AuthenticatedHomeRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/login': typeof LoginRoute
  '/posts': typeof PostsRoute
  '/home': typeof AuthenticatedHomeRouteWithChildren
  '/demo/simple-table': typeof DemoSimpleTableRoute
  '/home/clients': typeof AuthenticatedHomeClientsRoute
  '/home/programs': typeof AuthenticatedHomeProgramsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/home/settings/exercises/configuration': typeof AuthenticatedHomeSettingsExercisesConfigurationRoute
  '/home/settings/exercises/library': typeof AuthenticatedHomeSettingsExercisesLibraryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/login': typeof LoginRoute
  '/posts': typeof PostsRoute
  '/home': typeof AuthenticatedHomeRouteWithChildren
  '/demo/simple-table': typeof DemoSimpleTableRoute
  '/home/clients': typeof AuthenticatedHomeClientsRoute
  '/home/programs': typeof AuthenticatedHomeProgramsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/home/settings/exercises/configuration': typeof AuthenticatedHomeSettingsExercisesConfigurationRoute
  '/home/settings/exercises/library': typeof AuthenticatedHomeSettingsExercisesLibraryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/admin': typeof AdminRoute
  '/login': typeof LoginRoute
  '/posts': typeof PostsRoute
  '/_authenticated/home': typeof AuthenticatedHomeRouteWithChildren
  '/demo/simple-table': typeof DemoSimpleTableRoute
  '/_authenticated/home/clients': typeof AuthenticatedHomeClientsRoute
  '/_authenticated/home/programs': typeof AuthenticatedHomeProgramsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/_authenticated/home/settings/exercises/configuration': typeof AuthenticatedHomeSettingsExercisesConfigurationRoute
  '/_authenticated/home/settings/exercises/library': typeof AuthenticatedHomeSettingsExercisesLibraryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/login'
    | '/posts'
    | '/home'
    | '/demo/simple-table'
    | '/home/clients'
    | '/home/programs'
    | '/api/auth/$'
    | '/demo/api/names'
    | '/demo/start/api-request'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/home/settings/exercises/configuration'
    | '/home/settings/exercises/library'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/login'
    | '/posts'
    | '/home'
    | '/demo/simple-table'
    | '/home/clients'
    | '/home/programs'
    | '/api/auth/$'
    | '/demo/api/names'
    | '/demo/start/api-request'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/home/settings/exercises/configuration'
    | '/home/settings/exercises/library'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/admin'
    | '/login'
    | '/posts'
    | '/_authenticated/home'
    | '/demo/simple-table'
    | '/_authenticated/home/clients'
    | '/_authenticated/home/programs'
    | '/api/auth/$'
    | '/demo/api/names'
    | '/demo/start/api-request'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/_authenticated/home/settings/exercises/configuration'
    | '/_authenticated/home/settings/exercises/library'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AdminRoute: typeof AdminRoute
  LoginRoute: typeof LoginRoute
  PostsRoute: typeof PostsRoute
  DemoSimpleTableRoute: typeof DemoSimpleTableRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  DemoApiNamesRoute: typeof DemoApiNamesRoute
  DemoStartApiRequestRoute: typeof DemoStartApiRequestRoute
  DemoStartSsrDataOnlyRoute: typeof DemoStartSsrDataOnlyRoute
  DemoStartSsrFullSsrRoute: typeof DemoStartSsrFullSsrRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/posts': {
      id: '/posts'
      path: '/posts'
      fullPath: '/posts'
      preLoaderRoute: typeof PostsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/simple-table': {
      id: '/demo/simple-table'
      path: '/demo/simple-table'
      fullPath: '/demo/simple-table'
      preLoaderRoute: typeof DemoSimpleTableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/home': {
      id: '/_authenticated/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AuthenticatedHomeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/demo/start/api-request': {
      id: '/demo/start/api-request'
      path: '/demo/start/api-request'
      fullPath: '/demo/start/api-request'
      preLoaderRoute: typeof DemoStartApiRequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/api/names': {
      id: '/demo/api/names'
      path: '/demo/api/names'
      fullPath: '/demo/api/names'
      preLoaderRoute: typeof DemoApiNamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/home/programs': {
      id: '/_authenticated/home/programs'
      path: '/programs'
      fullPath: '/home/programs'
      preLoaderRoute: typeof AuthenticatedHomeProgramsRouteImport
      parentRoute: typeof AuthenticatedHomeRoute
    }
    '/_authenticated/home/clients': {
      id: '/_authenticated/home/clients'
      path: '/clients'
      fullPath: '/home/clients'
      preLoaderRoute: typeof AuthenticatedHomeClientsRouteImport
      parentRoute: typeof AuthenticatedHomeRoute
    }
    '/demo/start/ssr/full-ssr': {
      id: '/demo/start/ssr/full-ssr'
      path: '/demo/start/ssr/full-ssr'
      fullPath: '/demo/start/ssr/full-ssr'
      preLoaderRoute: typeof DemoStartSsrFullSsrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/data-only': {
      id: '/demo/start/ssr/data-only'
      path: '/demo/start/ssr/data-only'
      fullPath: '/demo/start/ssr/data-only'
      preLoaderRoute: typeof DemoStartSsrDataOnlyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/home/settings/exercises/library': {
      id: '/_authenticated/home/settings/exercises/library'
      path: '/settings/exercises/library'
      fullPath: '/home/settings/exercises/library'
      preLoaderRoute: typeof AuthenticatedHomeSettingsExercisesLibraryRouteImport
      parentRoute: typeof AuthenticatedHomeRoute
    }
    '/_authenticated/home/settings/exercises/configuration': {
      id: '/_authenticated/home/settings/exercises/configuration'
      path: '/settings/exercises/configuration'
      fullPath: '/home/settings/exercises/configuration'
      preLoaderRoute: typeof AuthenticatedHomeSettingsExercisesConfigurationRouteImport
      parentRoute: typeof AuthenticatedHomeRoute
    }
  }
}

interface AuthenticatedHomeRouteChildren {
  AuthenticatedHomeClientsRoute: typeof AuthenticatedHomeClientsRoute
  AuthenticatedHomeProgramsRoute: typeof AuthenticatedHomeProgramsRoute
  AuthenticatedHomeSettingsExercisesConfigurationRoute: typeof AuthenticatedHomeSettingsExercisesConfigurationRoute
  AuthenticatedHomeSettingsExercisesLibraryRoute: typeof AuthenticatedHomeSettingsExercisesLibraryRoute
}

const AuthenticatedHomeRouteChildren: AuthenticatedHomeRouteChildren = {
  AuthenticatedHomeClientsRoute: AuthenticatedHomeClientsRoute,
  AuthenticatedHomeProgramsRoute: AuthenticatedHomeProgramsRoute,
  AuthenticatedHomeSettingsExercisesConfigurationRoute:
    AuthenticatedHomeSettingsExercisesConfigurationRoute,
  AuthenticatedHomeSettingsExercisesLibraryRoute:
    AuthenticatedHomeSettingsExercisesLibraryRoute,
}

const AuthenticatedHomeRouteWithChildren =
  AuthenticatedHomeRoute._addFileChildren(AuthenticatedHomeRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedHomeRoute: typeof AuthenticatedHomeRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedHomeRoute: AuthenticatedHomeRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AdminRoute: AdminRoute,
  LoginRoute: LoginRoute,
  PostsRoute: PostsRoute,
  DemoSimpleTableRoute: DemoSimpleTableRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  DemoApiNamesRoute: DemoApiNamesRoute,
  DemoStartApiRequestRoute: DemoStartApiRequestRoute,
  DemoStartSsrDataOnlyRoute: DemoStartSsrDataOnlyRoute,
  DemoStartSsrFullSsrRoute: DemoStartSsrFullSsrRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
